# Generated by Django 2.2.6 on 2020-03-03 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('email', models.EmailField(max_length=71, null=True, verbose_name='Email')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_de_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Sexo')),
                ('endereco', models.CharField(max_length=50, verbose_name='Endereço')),
                ('observacao_endereco', models.CharField(max_length=50, verbose_name='Obs')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=20, verbose_name='Estado')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('telefone', models.CharField(max_length=13, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=13, verbose_name='Celular')),
                ('gerente', models.BooleanField(default=False)),
                ('nome_usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
