# Generated by Django 2.2.6 on 2020-03-12 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gerente',
            new_name='is_gerente',
        ),
    ]
