# Generated by Django 2.2.6 on 2020-05-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200525_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(upload_to='produtos/imagens/', verbose_name='Imagem do Produto'),
        ),
    ]
