# Generated by Django 3.0.7 on 2020-06-10 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200528_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoDeCreditoDebito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_no_cartao', models.CharField(max_length=100, verbose_name='Nome No Cartao')),
                ('numero_do_cartao', models.CharField(max_length=16, verbose_name='Número do Cartão')),
                ('mes_data_de_expiracao', models.CharField(max_length=2, verbose_name='Mês ')),
                ('ano_data_de_expiracao', models.CharField(max_length=2, verbose_name='Ano ')),
                ('codigo_cvv', models.CharField(max_length=4, verbose_name='Código de segurança (CVV)')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='data_da_compra',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_de_pagamento',
            field=models.PositiveIntegerField(choices=[[67, 'Boleto'], [34, 'Cartão de Crédito'], [89, 'Cartão de Débito']], default=67, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='status_da_compra',
            field=models.PositiveIntegerField(choices=[[55, 'Efetuado'], [56, 'Aguardando Pagamento'], [57, 'Pagamento Aprovado'], [58, 'Preparando Entrega'], [59, 'Transportadora'], [60, 'Pedidos Entregues']], default=55, verbose_name='Status da Compra'),
        ),
    ]
