# Generated by Django 3.0.7 on 2020-06-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200610_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='Cartao_de_cedito_debito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Produto', to='products.CartaoDeCreditoDebito'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_da_compra',
            field=models.PositiveIntegerField(choices=[[55, 'Efetuado'], [56, 'Aguardando Pagamento'], [57, 'Pagamento Aprovado'], [58, 'Preparando Entrega'], [59, 'Transportadora'], [60, 'Pedidos Entregues']], default=[55, 'Efetuado'], verbose_name='Status da Compra'),
        ),
    ]
