# Generated by Django 3.0.7 on 2020-06-11 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200610_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='Cartao_de_cedito_debito',
            new_name='cartao_de_credito_ou_debito',
        ),
        migrations.AlterField(
            model_name='compra',
            name='status_da_compra',
            field=models.PositiveIntegerField(choices=[[55, 'Efetuado'], [56, 'Aguardando Pagamento'], [57, 'Pagamento Aprovado'], [58, 'Preparando Entrega'], [59, 'Transportadora'], [60, 'Pedidos Entregues']], default=55, verbose_name='Status da Compra'),
        ),
    ]
